version: "3.7"

services:
  db:
    image: postgres

    environment:
      POSTGRES_PASSWORD: postgres

  dj:
    container_name: dj
    build: django
    command: python manage.py runserver 0.0.0.0:90
    volumes:
      - ./django:/code
    ports:
      - "90:90"
    depends_on:
      - db


